name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - run: pip install poetry
      - run: poetry install
      - run: poetry run black . --check
      - run: poetry run ruff .
      - run: poetry run mypy .
      - run: poetry run pytest --cov=neat_html --cov-fail-under=100
